apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ include "controle-contas.namespace" . }}
  labels:
    app: {{ include "controle-contas.name" . }}
type: Opaque
data:
    database_uri: {{ printf "postgresql://%s:%s@%s-db:%s/postgres" .Values.global.database_uri.username .Values.global.database_uri.password .Release.Name .Values.global.database_uri.port | b64enc }}
    secret_key: {{ .Values.application.secret.secret_key | b64enc }}
    jwt_secret_key: {{ .Values.application.secret.jwt_secret_key | b64enc }}
