{{- if .Values.database.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ include "controle-contas.name" . }}
  name: {{ .Release.Name }}-db
  namespace: {{ include "controle-contas.namespace" . }}
spec:
  serviceName: {{ include "controle-contas.name" . }}-db
  replicas: {{ .Values.database.statefulset.replicas }}
  selector:
    matchLabels:
      app: {{ include "controle-contas.name" . }}-db
  template:
    metadata:
      labels:
        app: {{ include "controle-contas.name" . }}-db
    spec:
      containers:
      - image: {{ .Values.database.statefulset.image }}
        name: postgres
        ports:
          - containerPort: 5432
        resources:
          requests:
            memory: "400Mi"
            cpu: "0.5"
          limits:
            memory: "600Mi"
            cpu: "0.8"
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          - name: POSTGRES_DB
            value: postgres
      restartPolicy: Always
{{- end -}}
