apiVersion: v1
kind: Secret
metadata:
  name: {{ include "controle-contas.name" . }}-secret
  namespace: {{ include "controle-contas.namespace" . }}
  labels:
    app: {{ include "controle-contas.name" . }}
type: Opaque
data:
  DATABASE_URI: {{ printf "postgresql://%s:%s@%s-db:%s/postgres" .Values.global.database_uri.username .Values.global.database_uri.password .Release.Name .Values.global.database_uri.port | b64enc }}
  SECRET_KEY: {{ .Values.application.secret.secret_key | b64enc }}
  JWT_SECRET_KEY: {{ .Values.application.secret.jwt_secret_key | b64enc }}
