---
# tasks file for ansible/roles/common

- name: Install dependencies
  ansible.builtin.apt:
    pkg:
    - net-tools
    - vim
    - curl
    - tmux
    - gpg
    state: latest
    update_cache: true
