---
- name: Install Helm
  block:
    - name: Download helm
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: 0700
      register: download

    - name: Install Helm
      ansible.builtin.shell: /tmp/get_helm.sh
      when:
        - download.failed|bool == false
  when: "'control_plane' in group_names"
