---
# tasks file for ansible/roles/k8s

- name: Include Install docker and containerd
  ansible.builtin.include_tasks: install-docker.yml

- name: Include Install K8S
  ansible.builtin.include_tasks: install-k8s.yml
